<?php

namespace App\StateProcessor;

use ApiPlatform\Metadata\Operation;
use App\Dto\UserInputDto;
use App\Entity\User;

class UserStateProcessor extends StateProcessor
{
    /**
     * @inheritDoc
     * @param UserInputDto $data
     */
    protected function processPost(mixed $data, Operation $operation, array $uriVariables = [], array $context = [])
    {
        return parent::processPost(
            User::create(
                $data->getFirstName(),
                $data->getLastName(),
                $data->getAge(),
                $data->getEmail(),
            ),
            $operation,
            $uriVariables,
            $context
        );
    }

    protected function processPut(mixed $data, Operation $operation, array $uriVariables = [], array $context = [])
    {
        return parent::processPut($data, $operation, $uriVariables, $context); // TODO: Change the autogenerated stub
    }
}